name: Markdown Accessibility Helper
description: Suggests alt text for images in markdown files
branding:
  icon: image
  color: purple
# action runs when a pull request is opened or updated or when a push is made to the main branch
on:
  pull_request:
    paths:
      - '**/*.md'
    types: [opened, synchronize]
  push:
    branches:
      - main
    paths:
      - '**/*.md'

inputs:
  clone_url:
    description: The clone URL of the repository
    required: true
  branch:
    description: The branch of the repository
    required: true
  github_actor:
    description: The GitHub actor
    required: true
  github_token:
    description: The GitHub token
    required: true
  azure_subscription_key:
    description: The Azure subscription key
    required: true
  azure_endpoint:
    description: The Azure endpoint
    required: true
  alt_language:
    description: The language to use for the alt text
    required: false
jobs:
  suggest_alt_text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install requests

      - name: Suggest Alt Text
        env: 
          CLONE_URL: ${{ inputs.clone_url }}
          BRANCH: ${{ inputs.branch }}
          GITHUB_ACTOR: ${{ inputs.github_actor }}
          GITHUB_TOKEN: ${{ inputs.github_token }}

          # these are the repository secrets you need to set in your repo
          AZURE_SUBSCRIPTION_KEY: ${{inputs.azure_subscription_key}}}
          AZURE_ENDPOINT: ${{inputs.azure_endpoint}}
          # this is the language you want to use for the alt text and is optional
          # if not set, the default is English
          # Set it as a repository variable
          ALT_LANGUAGE: ${{inputs.alt_language}}
        run: python suggest_alt_text.py