name: Markdown Accessibility Helper
description: Suggests alt text for images in markdown files
branding:
  icon: image
  color: purple
# action runs when a pull request is opened or updated or when a push is made to the main branch
on:
  pull_request:
    paths:
      - '**/*.md'
    types: [opened, synchronize]
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  suggest_alt_text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install requests

      - name: Suggest Alt Text
        env: 
          CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # these are the repository secrets you need to set in your repo
          AZURE_SUBSCRIPTION_KEY: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          # this is the language you want to use for the alt text and is optional
          # if not set, the default is English
          # Set it as a repository variable
          ALT_LANGUAGE: ${{ vars.ALT_LANGUAGE }}
        run: python suggest_alt_text.py